### Numpy:Array and Vectorized Computation.

In [1]:
import numpy as np  

In [3]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [4]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [5]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [6]:
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

### Creating ndarrays

The easiest way to create an array is to use the array function. This accepts any sequence-like object (including other arrays) and produces a new NumPy array containing the passed data. For example, a list is a good candidate for conversion:

In [16]:
l = [6,7.5,8,0,1] 
arr = np.array(l)
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [21]:
arr.ndim

1

In [24]:
arr.shape,arr.dtype

((5,), dtype('float64'))

In [35]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2, dtype=np.float64)
arr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [36]:
arr2.ndim, arr2.dtype

(2, dtype('float64'))

In [23]:
arr2.shape

(2, 4)

In [31]:
np.empty((4, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [32]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
np.ones((3,3 ,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [37]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [39]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

### Arithmetic with NumPy Arrays
Arrays are important because they enable you to express batch operations on data without writing any for loops

In [40]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [41]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [55]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2,1:]

array([8, 9])

In [58]:
lower_dim_slice = arr2d[1, :2]
lower_dim_slice.shape

(2,)

In [48]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
old_value = arr3d[0].copy()
old_value

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr =  np.arange(10).reshape((2,5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
np.dot(arr.T, arr)

array([[25, 30, 35, 40, 45],
       [30, 37, 44, 51, 58],
       [35, 44, 53, 62, 71],
       [40, 51, 62, 73, 84],
       [45, 58, 71, 84, 97]])

In [63]:
arr.T @ arr

array([[25, 30, 35, 40, 45],
       [30, 37, 44, 51, 58],
       [35, 44, 53, 62, 71],
       [40, 51, 62, 73, 84],
       [45, 58, 71, 84, 97]])

In [68]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [67]:
samples = np.random.standard_normal(size=(4, 4))
samples

array([[ 0.78405345,  0.22932422,  0.07731698, -0.53370708],
       [ 1.31655979, -1.34604228, -1.14510588,  0.97692096],
       [-0.23796985,  0.13463686,  1.1645941 , -0.77006415],
       [-0.29353889,  0.02926591, -0.0410748 , -0.92102152]])

In [70]:
points = np.arange(-5, 5, 0.01)
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [71]:
points.shape

(1000,)

In [80]:
arr = np.random.standard_normal((4, 4))
arr

array([[ 0.51908241,  0.12786539,  0.16685731,  0.51492453],
       [-0.63831343,  0.61529061,  0.68243883, -0.13317714],
       [-0.44888012,  0.53506057, -0.63002897, -0.67051634],
       [-0.64859298,  0.11625226, -0.1792984 ,  0.04994715]])

In [91]:
(arr[0,0:].sum())/len(arr[0,0:])

0.3321824087374485

In [81]:
np.where(arr>0, 'Aaron', arr)

array([['Aaron', 'Aaron', 'Aaron', 'Aaron'],
       ['-0.6383134308857463', 'Aaron', 'Aaron', '-0.13317713584642826'],
       ['-0.44888011573561903', 'Aaron', '-0.6300289704549061',
        '-0.6705163407754698'],
       ['-0.6485929787811119', 'Aaron', '-0.179298399163625', 'Aaron']],
      dtype='<U32')

In [82]:
arr.mean()

-0.0013180204230310508

In [83]:
np.mean(arr)

-0.0013180204230310508

In [85]:
arr.sum()

-0.021088326768496812

In [96]:
(arr[0:,0].sum())/len(arr[0:,0])

-0.3041760295647763

In [98]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [99]:
np.save('../data/my_array', m)

In [100]:
np.load('../data/my_array.npy')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [103]:
y @ x

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [125]:
from numpy.linalg import inv, qr,det,eig,svd,matrix_rank
X = np.random.randn(5, 5)
mat = X.T @ X
mat

array([[ 5.56980963, -1.50471299, -4.56916227,  0.35659732, -0.10514774],
       [-1.50471299,  2.01693107,  1.62083301, -1.58447391, -0.99669864],
       [-4.56916227,  1.62083301,  9.27485771,  1.80675213, -2.0686191 ],
       [ 0.35659732, -1.58447391,  1.80675213,  2.82669624,  0.14101867],
       [-0.10514774, -0.99669864, -2.0686191 ,  0.14101867,  2.470489  ]])

In [110]:
inv(mat)

array([[ 0.22261227,  0.11415989, -0.00829958, -0.03002296,  0.2202466 ],
       [ 0.11415989,  0.60786318, -0.3913776 , -0.2244007 ,  0.21176052],
       [-0.00829958, -0.3913776 ,  0.55888955,  0.3666416 , -0.06797251],
       [-0.03002296, -0.2244007 ,  0.3666416 ,  0.72668145, -0.7362866 ],
       [ 0.2202466 ,  0.21176052, -0.06797251, -0.7362866 ,  1.9397505 ]])

In [111]:
mat @ inv(mat)

array([[ 1.00000000e+00, -8.99196854e-17, -9.71967676e-18,
        -4.09700815e-17,  9.01917641e-17],
       [-7.92445042e-18,  1.00000000e+00,  6.13336992e-17,
         5.51292887e-17, -5.29233428e-17],
       [-3.94991514e-17,  4.18989953e-16,  1.00000000e+00,
         3.86764472e-17, -1.45717128e-16],
       [-1.16474629e-16, -2.29403402e-16,  3.51889314e-16,
         1.00000000e+00, -3.51593407e-16],
       [-5.56982195e-17, -5.71657411e-17,  1.14610254e-16,
         2.28100558e-17,  1.00000000e+00]])

In [108]:
mat @ inv(mat)

array([[ 1.00000000e+00, -5.05010745e-14, -1.63467739e-15,
        -2.65151603e-16, -8.57687867e-14],
       [-2.10182902e-14,  1.00000000e+00,  1.00960788e-14,
        -2.64392804e-15, -3.92614435e-14],
       [ 3.91980268e-16,  5.93533851e-15,  1.00000000e+00,
         1.92117469e-15,  3.60726622e-14],
       [-6.25299885e-15,  1.41212434e-14,  2.50856599e-15,
         1.00000000e+00, -1.10812755e-14],
       [-6.99161945e-15,  1.06648799e-14, -6.97650371e-15,
         2.01275511e-15,  1.00000000e+00]])

In [115]:
det(mat)

27.19095580640974

In [121]:
eig_values, eig_vectors = eig(mat)
eig_values,eig_vectors

(array([1.40631019e+01, 7.85123596e+00, 1.08242863e-03, 1.46921155e+00,
        3.09617401e+00]),
 array([[ 0.88443185,  0.191529  , -0.2617066 , -0.32929419,  0.06459049],
        [ 0.22080607, -0.33598626, -0.47307395,  0.78259649,  0.04584413],
        [-0.04184979,  0.04763175,  0.09713495,  0.03282218,  0.99270707],
        [-0.34074607, -0.30362455, -0.73967837, -0.48653716,  0.08866648],
        [ 0.22619833, -0.86946721,  0.38878196, -0.20325442,  0.01993291]]))

In [122]:
svd(mat)

SVDResult(U=array([[-0.88443185,  0.191529  , -0.06459049, -0.32929419, -0.2617066 ],
       [-0.22080607, -0.33598626, -0.04584413,  0.78259649, -0.47307395],
       [ 0.04184979,  0.04763175, -0.99270707,  0.03282218,  0.09713495],
       [ 0.34074607, -0.30362455, -0.08866648, -0.48653716, -0.73967837],
       [-0.22619833, -0.86946721, -0.01993291, -0.20325442,  0.38878196]]), S=array([1.40631019e+01, 7.85123596e+00, 3.09617401e+00, 1.46921155e+00,
       1.08242863e-03]), Vh=array([[-0.88443185, -0.22080607,  0.04184979,  0.34074607, -0.22619833],
       [ 0.191529  , -0.33598626,  0.04763175, -0.30362455, -0.86946721],
       [-0.06459049, -0.04584413, -0.99270707, -0.08866648, -0.01993291],
       [-0.32929419,  0.78259649,  0.03282218, -0.48653716, -0.20325442],
       [-0.2617066 , -0.47307395,  0.09713495, -0.73967837,  0.38878196]]))

In [123]:
qr(mat)

QRResult(Q=array([[-0.91398207,  0.18969648, -0.04056196, -0.24201905, -0.26159802],
       [-0.1492738 , -0.63842635, -0.06129169,  0.58514654, -0.47326102],
       [ 0.02123537,  0.00591838, -0.99493263, -0.01378799,  0.09712353],
       [ 0.35419617, -0.04941062, -0.05704876, -0.56755667, -0.73941094],
       [-0.12825067, -0.74427858,  0.03811234, -0.52604147,  0.38913876]]), R=array([[-1.25393594e+01, -2.72164145e+00,  4.91768446e-01,
         5.00707078e+00, -2.34917460e+00],
       [ 0.00000000e+00, -3.24588837e+00,  3.03121316e-01,
        -1.31020786e+00, -6.51810381e+00],
       [ 0.00000000e+00,  0.00000000e+00, -3.09867951e+00,
        -2.17160975e-01,  3.61026976e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.54827967e+00, -2.94568318e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.78415312e-03]]))

In [126]:
matrix_rank(mat)

5

In [127]:
import numba as nb

ModuleNotFoundError: No module named 'numba'